title: [CoMP-Py 2021](https://comppy.iiita.ac.in/)
logo: 
description: A hands-on tutorial on molecular dynamics algorithm in python for beginners.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
